# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'calculation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculation.proto\x12\x1e\x63om.danielang.calculation.grpc\"\x8c\x01\n\x12\x43\x61lculationRequest\x12\x12\n\nexpression\x18\x01 \x01(\t\x12H\n\nparameters\x18\x02 \x03(\x0b\x32\x34.com.danielang.calculation.grpc.CalculationParameter\x12\x18\n\x10\x63\x61lculation_type\x18\x03 \x01(\t\"3\n\x14\x43\x61lculationParameter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"a\n\x13\x43\x61lculationResponse\x12\x15\n\rresponse_code\x18\x01 \x01(\t\x12\x14\n\x0cresponse_msg\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\x01\x12\r\n\x05latex\x18\x04 \x01(\t2\x89\x01\n\x11\x43\x61lculatorService\x12t\n\tCalculate\x12\x32.com.danielang.calculation.grpc.CalculationRequest\x1a\x33.com.danielang.calculation.grpc.CalculationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALCULATIONREQUEST']._serialized_start=54
  _globals['_CALCULATIONREQUEST']._serialized_end=194
  _globals['_CALCULATIONPARAMETER']._serialized_start=196
  _globals['_CALCULATIONPARAMETER']._serialized_end=247
  _globals['_CALCULATIONRESPONSE']._serialized_start=249
  _globals['_CALCULATIONRESPONSE']._serialized_end=346
  _globals['_CALCULATORSERVICE']._serialized_start=349
  _globals['_CALCULATORSERVICE']._serialized_end=486
# @@protoc_insertion_point(module_scope)
